// <auto-generated />

using Neo.VM.Harness;
using System.Text.Json;

var res = Harness.Run(args);
var msg = $"{{\"status\":\"{res.status}\",\"errmsg\":\"{res.errmsg}\",\"estack\":{res.estack}}}";
var options = new JsonSerializerOptions(){
    WriteIndented = true
};

var jsonElement = JsonSerializer.Deserialize<JsonElement>(msg);

Console.Write(JsonSerializer.Serialize(jsonElement, options));
